### ISSUE TITLE
Incompatibility with wolf armor: Process hangs up on launch

### ISSUE THREAD

**Issue by HariboTer** [zabi94/MaxPotionIDExtender#4]
Here's the log:

[latest.log](https://github.com/zabi94/MaxPotionIDExtender/files/5737555/latest.log)

I'm running about 440 mods, but wolf armor is explicitly mentioned and removing either wolf armor or maxpotidext enables the game to launch again. However, I do have to admit that I can not reproduce the issue using only those two mods. I tried also adding VanillaFix and a few other mods to no avail. I'd be glad to assist in further testing if required.

**Comment by zabi94** [comment]
The problem here is that wolfarmor uses a mixin to change the base game, while I use a raw asm modification.

When the mixin tries to apply WA's potion tweaks into memory, it finds that the class has already been loaded by my mod and crashes.

I don't know how to fix that without rewriting the old mod to use mixins, which I'm not doing cause I don't really have the time to, currently
